CREATE DATABASE 65G;
USE 65G
CREATE TABLE student_data (ID INT, NAME VARCHAR(255), BRANCH VARCHAR(255), PERCENTAGE INT, EMAIL VARCHAR(255));
INSERT INTO  student_data(ID, NAME, BRANCH, PERCENTAGE, EMAIL) VALUES (1, 'Ram', 'IT', 85, 'ram123@gmail.com');
INSERT INTO  student_data(ID, NAME, BRANCH, PERCENTAGE, EMAIL) VALUES (2, 'Rahim', 'EEE', 95, 'rahim123@gmail.com');
INSERT INTO  student_data(ID, NAME, BRANCH, PERCENTAGE, EMAIL) VALUES (3, 'Robert', 'ECE', 90, 'robert123@gmail.com');
