/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "power.h"

int *
power_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;
    printf("Power Function was called for inputs %d^%d\n",argp->x, argp->y );
    result = 1;
    for(int i =0; i< argp->y; i++){
        result *= argp->x;   
    }
	return &result;
}
